site_name: gocryptfs
theme: readthedocs
theme_dir: xreadthedocs
pages:
- Home: index.md
- Quickstart: quickstart.md
- Security: security.md
- Comparison with other projects: comparison.md
- Releases: releases.md
